apiVersion: batch/v1
kind: Job
metadata:
  name: temperature-job
spec:
  template:
    metadata:
      labels:
        app: temperature-job
    spec:
      containers:
        - name: temperature-job
          image: beam-python-harness:2.56.0
          command: ["python"]
          args:
            - "-m"
            - "temperature.run"
            - "--deploy"
            - "--input_topic=input-topic"
            - "--output_topic_above_20=output-topic-temperature-high"
            - "--output_topic_below_20=output-topic-temperature-low"
            - "--bootstrap_servers=demo-cluster-kafka-bootstrap.default.svc.cluster.local:9092"
            - "--runner=FlinkRunner"
            - "--flink_master=temperature-cluster-rest:8081"
            - "--job_name=temperature-job"
            - "--streaming"
            - "--parallelism=3"
            - "--flink_submit_uber_jar"
            - "--environment_type=EXTERNAL"
            - "--environment_config=localhost:50000"
            - "--checkpointing_interval=10000"
      restartPolicy: Never
