apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: producer
        image: kafka-producer:latest 
        imagePullPolicy: Never
        env:
        - name: BOOTSTRAP_SERVERS
          value: "demo-cluster-kafka-bootstrap.default.svc.cluster.local:9092"
        - name: TOPIC_NAME
          value: "input-topic"
